In [1]:
%matplotlib inline

import os
import glob
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy.linalg as la

sns.set_context('notebook', font_scale=1.5)

**1**. Determine whether the following system of equations has no solution, infinite solutions or a unique solution *without solving the system*

$$\begin{eqnarray*}
x+2y-z+w &=& 2\\
3x-4y+2 w &=& 3\\
2y+z &=& 4\\
2x+2y-3z+2w&=&0\\
-2x+6y-z-w&=&-1
\end{eqnarray*}$$

In [2]:
A = np.array([[1,2,-1,1,2],[3,-4,0,2,3],[0,2,1,0,4],[2,2,-3,2,0],[-2,6,-1,-1,-1]])

In [3]:
np.linalg.matrix_rank(A)

3

In [4]:
np.linalg.det(A)

-3.1554436208840535e-30

In [5]:
np.linalg.svd(A)

(array([[ 0.09110569,  0.5266526 ,  0.00714716,  0.55214288, -0.63986245],
        [-0.65077439,  0.38342368,  0.0301255 ,  0.36840064,  0.54115839],
        [ 0.06655053,  0.54048886, -0.69939768, -0.46027176,  0.04935203],
        [ 0.11566084,  0.51281634,  0.71369199, -0.46027176,  0.04935203],
        [ 0.74188007,  0.14322891, -0.02297834,  0.36840064,  0.54115839]]),
 array([8.75873024e+00, 6.11226672e+00, 4.46372491e+00, 9.75624284e-16,
        1.86751596e-16]),
 array([[-0.3554917 ,  0.86782124, -0.12712091, -0.19648984, -0.25640586],
        [ 0.39528682,  0.40665672, -0.27286795,  0.35598965,  0.69079164],
        [ 0.35191782, -0.04827563, -0.6327994 ,  0.34002106, -0.59814204],
        [ 0.7397376 ,  0.25642633,  0.52598217, -0.20719068, -0.25970871],
        [-0.21521179,  0.11589483,  0.4819658 ,  0.82226566, -0.17843887]]))

**2**. Let $f(x)$ be a linear transformation of $\mathbb{R}^3$ such that
$$\begin{eqnarray*}
f(e_1) &=& (1,1,3)\\
f(e_2) &=& (1,0,4)\\
f(e_3) &=& (0,2,1)
\end{eqnarray*}$$

* Find a matrix representation for $f$. 
* Compute the matrix representation for $f$ in the basis$$\begin{eqnarray*}
v_1 &=& (2,3,3)\\
v_2 &=& (8,5,2)\\
v_3 &=& (1,0,5)
\end{eqnarray*}$$

In [6]:
A = np.array([[1,1,3],[1,0,4],[0,2,1]]).T
A

array([[1, 1, 0],
       [1, 0, 2],
       [3, 4, 1]])

In [7]:
C = np.array([[2,3,3],[8,5,2],[1,0,5]]).T
C

array([[2, 8, 1],
       [3, 5, 0],
       [3, 2, 5]])

In [8]:
la.solve(C, A @ C)

array([[ 3.59493671,  4.56962025,  5.48101266],
       [-0.55696203, -0.34177215, -1.08860759],
       [ 2.26582278,  6.59493671, -1.25316456]])

**3**. Find the four fundamental subspaces of the matrix

$$
A = \pmatrix{
1 & 3 & 3 & 2 \\
2 & 6 & 9 & 7 \\
-1 & -3 & 3 & 4
}
$$

Check lecture notes

**4**. Find the least squares linear solution to the following data

```
y = [1,2,3,4]
x1 = [1,2,3,4]
x2 = [2,3,4,5]
```

That is, find the "best" intercept and slope for the variables `x1` and `x2`.

**5**. Find the coordinates of the vector $\pmatrix{1\\ 2 \\3}$ with respect to the eigenvectors of the following matrix.
```
array([[ 0.18673654,  0.20037016,  0.47406091],
       [ 0.21715108,  0.44708353,  0.79204575],
       [ 0.24299882,  0.51936745,  0.3061621 ]])
```

**6**. Consider the following system of equations:

$$\begin{align*}
2x_1& - x_2&    +x_x    &=& 6\\
-x_1& +2x_2& -  x_3 &=& 2\\
 x_1   &  -x_2& + x_3 &=& 1
\end{align*}$$

1. Consider the system in matrix form $Ax=b$ and define $A$, $b$ in numpy.
2. Show that $A$ is positive-definite
3. Use the appropriate matrix decomposition function in numpy and back-substitution to solve the system. Remember to use the structure of the problem to determine the appropriate decomposition.

**7**. You are given the following set of data to fit a quadratic polynomial to

```python
x = np.arange(10)
y = np.array([  1.58873597,   7.55101533,  10.71372171,   7.90123225,
                -2.05877605, -12.40257359, -28.64568712, -46.39822281,
                -68.15488905, -97.16032044])
```

- Find the least squares solution by using the normal equations $A^T A \hat{x} = A^T y$. 
- Plot the data together with the fitted polynomial. 




In [10]:
x = np.arange(10)
y = np.array([  1.58873597,   7.55101533,  10.71372171,   7.90123225,
                -2.05877605, -12.40257359, -28.64568712, -46.39822281,
                -68.15488905, -97.16032044])

In [11]:
A = np.c_[np.ones(10), x, x**2]
I = np.eye(10)
xhat = la.solve(A.T@A, A.T@y)
A@xhat - y

array([ 0.96206401,  0.27337758, -1.69811458, -1.77678962,  1.20967548,
        0.4975511 ,  1.602364  ,  0.13422035, -1.41217147,  0.20782315])

In [ ]:
M = np.array([[ 0.18673654,  0.20037016,  0.47406091],
       [ 0.21715108,  0.44708353,  0.79204575],
       [ 0.24299882,  0.51936745,  0.3061621 ]])

In [ ]:
v = np.array([1,2,3])
w = la.solve(M, v)
w

**8**. Find the minimum of the following quadratic function on $\mathbb{R}^4$ 

$$f(x) = x^TAx +b^Tx +c$$
where
$$A = \left(\begin{matrix}13&5&0&0\\5&7&0&0\\0&0&20&-7\\0&0&-7&12\end{matrix}\right), b = \left(\begin{matrix}1\\1\\1\\1\end{matrix}\right) \textrm {and } c = 2$$

and $x$ is a column vector, using a matrix decomposition method (library functions - no need to code your own).  Note: for full credit you should exploit matrix structure.